config/routes.rb
Rails.application.routes.draw do
  namespace :api do
    namespace :v1 do
      resources :links, only: [:update]
    end
  end

  root 'welcome#index'

  resources :users, only: [:new, :show, :create]

  get "login", to: "sessions#new"
  post "login", to: "sessions#create"
  delete "logout", to: "sessions#delete"

  resources :links, only: [:index, :create]
end

app/models/link.rb
require 'uri'

class Link < ActiveRecord::Base
  include ActiveModel::Validations
  validate :valid_link?

  validates :url, :title, presence: true, uniqueness: true

  def valid_link?
    uri = URI.parse(self.url)
    errors.add(:base, "Invalid url") unless uri.kind_of?(URI::HTTP)
  rescue URI::InvalidURIError
    false
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_secure_password
  validates :email, :username, :password, presence: true
  validates :email, confirmation: true, uniqueness: true
end

app/controllers/api/v1/links_controller.rb
class Api::V1::LinksController < ApplicationController
  respond_to :json

  def update
    link = Link.find_by(id: params[:id])
    respond_with link.update_attributes(link_params)
  end

  private

  def link_params
    params.require(:link).permit(:url, :title, :read)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end

  def create
    @link = Link.new(link_params)
    unless @link.save
      flash[:error] = @link.errors.full_messages.join(", ")
    end
    redirect_to links_path
  end

  private

  def link_params
    params.require(:link).permit(:url,
                                 :title)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(username: params[:login][:username])
    if @user && @user.authenticate(params[:login][:password])
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash.now[:errors] = "Invalid Login"
      render :new
    end
  end

  def delete
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def show
    if current_user && @user = User.find_by(id: params[:id])
      @user
    elsif @user
      redirect_to login_path
    else
      redirect_to new_user_path
    end
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to user_path(@user)
    else
      flash[:error] = @user.errors.full_messages.join(", ")
      redirect_to new_user_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:email,
                                 :username,
                                 :password,
                                 :password_confirmation)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/api/v1/links_helper.rb
module Api::V1::LinksHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_flash.html.erb
<% flash.each do |name, message| %>
  <%= content_tag(:div, sanitize(message),
  class: "#{message}",
  :id => "flash_#{name}") %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav>
    <div class="nav-wrapper">
      <a href="#" class="brand-logo">ThoughtBox</a>
      <ul id="nav-mobile" class="right hide-on-med-and-down">
        <% if current_user %>
          <li>
            <%= "Welcome, #{current_user.username}." %>
          </li>
          <li>
            <%= link_to "Logout", logout_path, method: :delete %>
          </li>
            <% else %>
          <li>
            <%= link_to "Sign Up", new_user_path %>
          </li>
          <li>
            <%= link_to "Login", login_path %>
          </li>
        <% end %>
      </ul>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PracticeThoughtboxAssessment</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/navbar' %>

<%= render 'layouts/flash' %>

<%= yield %>

</body>
</html>

app/views/links/index.html.erb
<h3>Create a Link</h1>

<%= form_for :link do |f| %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <%= f.submit "Create Link" %>
<% end %>

<h3>All the Links</h1>

<% @links.each do |link| %>
  <div class="row" data-id="<%=link.id%>"
                   data-read="<%=link.read?%>"
                   id="link-<%=link.id%>">
    <ul class="col"><%= link.title %>
      <li>Url: <%= link.url %></li>
      <li class="read-status">Read? <%= link.read %></li>
    </ul>
    <button class="col read">Mark as Read</button>
    <button class="col unread">Mark as Unread</button>
  </div>
<% end %>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
<h3>Please enter your information to create an account.</h3>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <%= f.label :username %>
  <%= f.text_field :username %>
  <%= f.label :password %>
  <%= f.text_field :password %>
  <%= f.label :password_confirmation %>
  <%= f.text_field :password_confirmation %>
  <%= f.submit "Create Account" %>
<% end %>

app/views/users/show.html.erb
<h3>Welcome, <%=@user.username%></h3>

<%= link_to "Links", links_path %>

app/views/welcome/index.html.erb
<h3>Please <%= link_to "Sign Up", new_user_path %> or <%= link_to "Log In", login_path %></h3>